name: Context
on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!')
          }}
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: eccho "$GITHUB_CONTEXT" # purposeful typo
      - name: Dump job Context
        if: failure() # should still run, even though prev. step fails due to typo
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner Context
        if: always()
        env:
          JOB_RUNNER: ${{ toJson(runner) }}
        run: echo "$JOB_RUNNER"